### ISSUE TITLE
Wrong link and missing image in lesson 11 #wrapping-up

### ISSUE THREAD

**Issue by watershed** [hankchizljaw/learneleventyfromscratch.com#14]
This course is great, Andy. Thanks. I'm very happy to have bought it earlier in the year, even though I'm only now getting to it and it's now free!

In [Lession 11 Wrapping up](https://learneleventyfromscratch.com/lesson/11.html#wrapping-up) your reference to:

     http://localhost:8080https://piccalil.li/blog/

…should be:

     http://localhost:8080/blog/

…and you have a missing image:

<img width="786" alt="Screen Shot 2021-12-05 at 12 51 02" src="https://user-images.githubusercontent.com/219060/144747405-124c07cd-bf3e-451c-9c6f-9f2e713a75a4.png">

**Comment by tobiasziegler** [comment]
I just stumbled onto this issue with the blog links as well, but it's a bit broader than the single link in Lesson 11. It looks like this commit introduced the broken `/blog/` slugs and links, including in the `navigation.json` code in Lesson 7, etc.: https://github.com/hankchizljaw/learneleventyfromscratch.com/commit/c11b053c94bc3922a6ccd52e56744d847147ace6

Agreed on the quality of the course - thanks for making it available, Andy!

**Comment by hankchizljaw** [comment]
Fixed with #9
